use discord_webhook2::id::DiscordID;
use std::collections::BTreeMap;
use std::fmt::{Debug, DebugStruct};
use std::fs::File;
use std::io::{Read};
use std::io::Cursor;

use discord_webhook2::message::Message;
use discord_webhook2::webhook::DiscordWebhook;
use xcap::image::RgbaImage;

pub struct send_message{
    pub title:String,
    pub description:String,
    pub author:Option<String>,
    pub footer: Option<String>,
    pub field_1: Vec<String>,
    pub field_2: Vec<String>,
    pub field_3: Vec<String>,

}
impl send_message{
    pub async fn sendMessage(self) -> DiscordID {

        let webhook = DiscordWebhook::new("https://discord.com/api/webhooks/1297187641636159538/58LmoxoSJRxLzByNcGmEQ8v1ZpuIMb_RXku5WynFoI-R6IpNGm_qV_y4TOXUmCn3KKxF").unwrap();

        webhook
            .send(&Message::new(|message| {
                message.embed(|embed| {
                    embed
                        .title(self.title)
                        .description(self.description)
                        .footer(|footer| footer.text("generated by rustware"))
                        .author(|author| author.name(
                            match &self.author{
                                None => "None Provided",
                                Some(e) => e,
                            }
                        ))
                        .field(|field| field.name(&self.field_1[0]).value(&self.field_1[1]))
                        .field(|field| field.name(&self.field_2[0]).value(&self.field_2[1]))
                        .field(|field| field.name(&self.field_3[0]).value(&self.field_3[1]))
                        .color(0x00BBFF)

                })
            }))
            .await
            .unwrap()


    }
}
pub async fn send_files(file_path:&str) {
    let webhook = DiscordWebhook::new("https://discord.com/api/webhooks/1297187641636159538/58LmoxoSJRxLzByNcGmEQ8v1ZpuIMb_RXku5WynFoI-R6IpNGm_qV_y4TOXUmCn3KKxF").unwrap();

    let mut files:BTreeMap<String,Vec<u8>> = BTreeMap::new();
    let file = File::open(file_path);
    let mut bytes:Vec<u8> = Vec::new();
    file.unwrap().read_to_end(&mut bytes);
    files.insert(
        String::from(file_path),
        Vec::from(bytes),
    );


    webhook
        .send_with_files(
            &Message::new(|message| {
                message.embed(|embed| embed.title("hi!"))
            }),
            files,
        )
        .await
        .unwrap();

}

pub async fn send_img_RGBA(Image: Vec<RgbaImage>) {
    let webhook = DiscordWebhook::new("https://discord.com/api/webhooks/1297187641636159538/58LmoxoSJRxLzByNcGmEQ8v1ZpuIMb_RXku5WynFoI-R6IpNGm_qV_y4TOXUmCn3KKxF").unwrap();

    let mut files:BTreeMap<String,Vec<u8>> = BTreeMap::new();
    if Image.len() == 0{

    }

    let mut bytes:Vec<u8> = Vec::new();
    files.insert(
        String::from("image"),
        Vec::from(bytes),
    );


    webhook
        .send_with_files(
            &Message::new(|message| {
                message.embed(|embed| embed.title("hi!"))
            }),
            files,
        )
        .await
        .unwrap();

}
